n = (input ('Escreva algo: '))
print ('O tipo primitivo desse valor é,' , type(n))
print ('A primeira letra é minuscula?' , n.islower())
print ('Está em caixa alta?', n.isupper())
print ('É um número?', n.isnumeric())
print('É soemente espaço?',n.isspace())